PackageIdentifier: norc.norc-cli
PackageVersion: 0.2.2
InstallerType: portable
Scope: user
Commands:
  - norc
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/norcapp/norc-cli/releases/download/v0.2.2/norc-win-x64.exe
    InstallerSha256: 80928E7BC4ADAF37BC110BF2FFE7A8661FE5CDE76E350F6DBC1C6BDBB5ED1CFF
ManifestType: installer
ManifestVersion: 1.6.0
